### ISSUE TITLE
the size of image can't zoom

### ISSUE THREAD

**Issue by qigeligedongdongqiang** [MatteoGabriele/vue-progressive-image#10]
如果原图大小是300x300px,设置img标签的width大于300px图片无法缩放，仍显示原图的width
the size of a image is 300x300px,when setting the img label style width <300px ,it's normal. but when setting the img label style width >300px,it will be abnormal.

**Comment by MatteoGabriele** [comment]
could you rewrite it all in English, please?

**Comment by qigeligedongdongqiang** [comment]
For example:
Here i have a imageCase.vue,

```
<template>
	<li>
		<router-link :to=imgObj.link>
			<div id="imgCase">
				<progressive-img :src=imgObj.img :style="{width: imgObj.width,height: imgObj.height}" alt="" />
			</div>
		</router-link>
	</li>
</template>

<script>
export default {
	name: 'imageCase',
	props: [
		'imgObj'
	],
}	
</script>

<style lang="scss" scoped>
li {
	list-style: none;
	position: relative;
}

#imgCase:after {
  opacity: 0;
  background: black;
  position: absolute;
  z-index: 1;
  content: '';
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;			  
  transition: .2s ease-out;
  -webkit-transition: .2s ease-out; 
}

#imgCase:hover:after {
	opacity: 0.5;
}	
</style>
```

then i use the imageCase in another vue like this,

```
<template>
	<div id="design">
		<ul>
			<li 
			is="image-case" 
			v-for="item in items" 
			:imgObj="{img:item.img,link:item.link,width:'1025px',height:'245px'}"
			></li>
		</ul>
	</div>
</template>
```

Now the problem comes,if the source image is a picture which width >1025px and height >245px, it can be zoom and works well.But when the width <1025px or height < 245px,it will be abnormal,the image can't zoom to fill .

**Comment by MatteoGabriele** [comment]
Hi @qigeligedongdongqiang 
could you please provide a public repository with the example that has the issue you're talking about?
thanks a lot

**Comment by MatteoGabriele** [comment]
i close this issue for inactivity, open it in anytime if you provide more info
