### ISSUE TITLE
Safari and Mobile Support

### ISSUE THREAD

**Issue by dmattia** [MatteoGabriele/vue-progressive-image#12]
I am using this component in an app of mine and it works fine on Chrome.  However, it fails to load the desired image on mobile chrome (iOS), mobile Safari (iOS), and Mac Safari v10.1.2.  On all three browsers, it only displays the thumbnail image permanently and console.errors the message

`The index is not in the allowed range.`

**Comment by MatteoGabriele** [comment]
Thanks for you feedback :)
bug fixed with v2.1.1
