### ISSUE TITLE
Error using blur prop on progressive-img component

### ISSUE THREAD

**Issue by inbrighttech** [MatteoGabriele/vue-progressive-image#15]
Thank you for this,

Need a little help here, kind of a noob. I was testing the placeholder with blur as in the README:
.....
src="https://unsplash.it/1920/1080?image=10"
placeholder="https://unsplash.it/1920/1080?image=10" 
blur="30"
....

And get this error:

> [Vue warn]: Invalid prop: type check failed for prop "blur". Expected Number, got String.
> 
> found in
> 
> ---> <ProgressiveImg>

Tried changing
blur="30" to  blur=30.... No success

**Comment by MatteoGabriele** [comment]
hi @inbrighttech 
you need to prepend the attribute with a semicolon, otherwise the value is interpreted as a string.
The example has a typo that I didn't see until now, sorry :)

```html
<progressive-image 
  src="https://unsplash.it/1920/1080?image=10"
  placeholder="https://unsplash.it/1920/1080?image=10"
  :blur="30"
/>
```
I'm working on some nice example to add to the repo so that's more easy to learn
