### ISSUE TITLE
Problems with progressive-background

### ISSUE THREAD

**Issue by adavie1** [MatteoGabriele/vue-progressive-image#17]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

Installed OK and testing the progressive-background component. It loads the image, but it pushes the content that ought to be on top, below.

What are you reporting?

Currently I'm loading the image with as follows:
```
    <div :style="'background-image: url(../static/bg-image.png); no-repeat center center fixed; ' +
    '-webkit-background-size: cover;  -moz-background-size: cover;' +
    '-o-background-size: cover; background-size: cover;'">
... Login form
</div>
```
Replaced with:
```
<progressive-background src="../static/bg-image.png">
... Login form
</progressive-background>
```

Tell us what you think should happen.

The Login form content should be on top of the image.
![image](https://user-images.githubusercontent.com/3030402/29742773-8068f53c-8ab7-11e7-8a8c-07cffb1033e3.png)

Tell us what actually happens.
The image covers the login form
![image](https://user-images.githubusercontent.com/3030402/29742768-528c9006-8ab7-11e7-81dd-c0eb4f7d491a.png)

### Environment

Run this command in the project folder and fill in the result:

`npm ls vue-progressive-image`: **2.1.2**

Then, specify:

1. Operating system: Linux - **Ubuntu 16.04**
2. Browser and version: **Chrome v.60**

**Comment by MatteoGabriele** [comment]
bug fixed with vue-progressive-image@2.1.3

thanks for your feedback :)
