### ISSUE TITLE
[Feature Request] - Background Video

### ISSUE THREAD

**Issue by adavie1** [MatteoGabriele/vue-progressive-image#19]
@MatteoGabriele thanks for creating a great component and being very responsive in fixing things. As a suggestion for a future component, have you considered doing a background-video component?
I tried another component for this, but it had issues.

I've got it working outside of Vue using this [codepen](https://codepen.io/dudleystorey/pen/knqyK?editors=1010)

**Comment by MatteoGabriele** [comment]
Hi @adavie1 thanks a lot!

Managing a video it's not really the same as managing an image and would probably go outside the scope of this package.
Could be maybe a suggestion for another package
I'll let you know if maybe I'm going to make it, It's a good idea.

Thanks a lot for your feedback
