### ISSUE TITLE
onLoad Events

### ISSUE THREAD

**Issue by appinteractive** [MatteoGabriele/vue-progressive-image#2]
I would need an simple onLoad event for each image (full and placeholder) dispatched. Could you provide the possibility to pass such events?

`<progressive-img @onLoad="onLoadMethod" @onLoadPlaceholder="onLoadPlaceholderMethod" />`

**Comment by MatteoGabriele** [comment]
Sure, it's definitely handy!

thanks for suggesting that

**Comment by MatteoGabriele** [comment]
published new v1.4.0 

here the new doc section
https://github.com/MatteoGabriele/vue-progressive-image#events

thanks again
