### ISSUE TITLE
Cannot get this to work inside of my component...

### ISSUE THREAD

**Issue by rchrdnsh** [MatteoGabriele/vue-progressive-image#21]
Soooo, I can get this to work with a basic image with basic CSS, like so:

```
progressive-img {
  width: 100%;
  height: auto;
}
```

...but I cannot seem to get it to work with more specific CSS inside of a custom vue component. the image simply does not show up at all.

Can you see anything in this CSS that might be causing an issue with the plugin?

This is the CSS of the parent component:

```
.component {
  width: 100%;
  height: calc(100vh - 48px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  position: relative;
  background: url(../../assets/images/logos/arrow-favicon-blue-10-percent.svg) no-repeat center 25vh, #091830;
}
```

and here is the CSS of the progressive-image, which is a child of the parent .component:

```
progressive-img {
  width: 100vw;
  height: calc(100vh - 48px);
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  object-fit: cover;
  z-index: 1;
}

@media screen and (orientation: landscape) {
  progressive-img {
    width: 70vw;
    height: 100vh;
  }
}
```

Please let me know if you see anything, or if you need any more information to understand better. I looks like the image tries to load by flickering for a split second, but then it's gone, if that helps at all.

...I think it's almost there! XD

R

**Comment by MatteoGabriele** [comment]
@rchrdnsh it shows for me, you are simply targeting the `progressive-img` as a tag that doesn't exist in your html: you need to add a class and apply your style.

**Comment by rchrdnsh** [comment]
ok @MatteoGabriele, I added a '.progressive-image' class to the tag and it is now working, except the image itself is not adhering to it's 'object-fit: cover' css property. The placeholder image does adhere to the 'object-fit: cover' css property, however, which seems a little bit odd:

<img width="1440" alt="screenshot 2017-09-26 13 48 24" src="https://user-images.githubusercontent.com/7884263/30883669-c3e9fb54-a2c1-11e7-8f0a-9ee1d3c7f309.png">

The regular image works just fine with the exact same CSS:

<img width="1440" alt="screenshot 2017-09-26 13 49 14" src="https://user-images.githubusercontent.com/7884263/30883685-d0fcb14c-a2c1-11e7-8708-3781f275847a.png">

...so I'm thinking it might be a bug in the plugin?

**Comment by MatteoGabriele** [comment]
you might want to use `progressive-background` for this, the `progressive-img` it maintains a responsive aspect ratio, that's why doesn't fit completely and also remember that when you add the object-fit property to your `.progressive-image` class, you are not actually targeting an img tag, but a bunch of divs and an image tag somewhere inside that structure: make sense that doesn't work :)

**Comment by rchrdnsh** [comment]
yes! progressive-background did the trick! smart idea as well @MatteoGabriele :-)

**Comment by rchrdnsh** [comment]
And I want to thank again for taking the time to make this...it really is a nice UX enhancement :-)

**Comment by MatteoGabriele** [comment]
@rchrdnsh thanks a lot :)
