### ISSUE TITLE
Can this be used in server-side rendering?

### ISSUE THREAD

**Issue by ghost** [MatteoGabriele/vue-progressive-image#22]
**The easiest example is how do I set up to use vue-progressive-image in nuxt.js?**

ssr: false, or if (process.BROWSER_BUILD) {} setting.

-- 
The error message is as follows.

_[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Billing hydration and performing full client-side render._

**Comment by skoulix** [comment]
If you are using the latest 1.0.0-rc11 nuxt.js version you can wrap the image component with the `<no-ssr>` tag and it will work. An example is

```
<no-ssr>
<progressive-img src="https://unsplash.it/1920/1080?image=10" />
</no-ssr>
```
The warnings should be gone.

**Comment by MatteoGabriele** [comment]
Hi @hyeokluv 
I actually don't use `document` or `window` objects, but during compilation a `document.create('style')` snippet is added to the distribution file and I guess is used to be able to inject the vue-progressive-image css.

The solution of @Skoulix it works just fine for Nuxt. Thanks :)

I don't really know how to avoid this plugin to break on SSR, if you have any ideas please let me know: I might have to check what the vue loaders are doing under the hood.

Thanks for your feedback

**Comment by MatteoGabriele** [comment]
@hyeokluv have you ever fixed this issue? 
Thanks

**Comment by MatteoGabriele** [comment]
close this issue for inactivity, fee free to open it again for any issues of PR

**Comment by sschadwick** [comment]
I'm running into a separate error when attempting to use this plugin with the latest version of nuxt. I get this error when attempting to install the plugin (before using the directive).

```
{ ReferenceError: document is not defined
    at o (node_modules/vue-progressive-image/dist/vue-progressive-image.js:6:0)
    at n (node_modules/vue-progressive-image/dist/vue-progressive-image.js:6:0)
```

**Comment by skoulix** [comment]
@sschadwick 

Try to load the plugin with SSR set to false, example:

`
plugins: [
  { src: '~plugins/vue-progressive-image', ssr:false }
]
`

**Comment by ghost** [comment]
+1
