### ISSUE TITLE
onerror url

### ISSUE THREAD

**Issue by arturogf93** [MatteoGabriele/vue-progressive-image#23]
Is there a way to put a placeholder if the url is broken?

**Comment by MatteoGabriele** [comment]
Hi @arturogf93 
not it's not possible now, but I can implement that: sounds like a nice feature.

thanks for your feedback

**Comment by MatteoGabriele** [comment]
I've added the `fallback` property so that you can basically load another image if the main one is broken

your can see it [here](https://github.com/MatteoGabriele/vue-progressive-image#image-fallback)

and I have also added the `onError` and `onErrorPlaceholder` events if you need to
