### ISSUE TITLE
Expected String, got Null.

### ISSUE THREAD

**Issue by johncloud200** [MatteoGabriele/vue-progressive-image#26]
`:src="post.image" fallback="no-image-available.png"`
Invalid prop: type check failed for prop "src". Expected String, got Null.

Solution :
`:src="post.image || 'no-image-available.png'" fallback="no-image-available.png"`

Can we accept null and go to fallback without got error?

**Comment by MatteoGabriele** [comment]
Yeah i thought about it few times, I was just passing an empty string as default, but I guess just accepting everything and let the developer decide could be a better solution.

Thanks for your feedback

**Comment by MatteoGabriele** [comment]
you can find the update on the latest v2.3.1
