### ISSUE TITLE
Bind all images are loaded

### ISSUE THREAD

**Issue by andrii-trush** [MatteoGabriele/vue-progressive-image#27]
Hello. I have several progressive-img components in my component. How can I bind all images were loaded dynamically.

**Comment by MatteoGabriele** [comment]
I'm sorry but I didn't quite understand, could you maybe add an example or be more specific?
thanks a lot

**Comment by MatteoGabriele** [comment]
I close this ticket for inactivity. feel free to open it again when you have more info
