### ISSUE TITLE
Invalid prop: type check failed for prop "aspectRatio". Expected Number, got String.

### ISSUE THREAD

**Issue by james-clare** [MatteoGabriele/vue-progressive-image#28]
### Description
Despite the prop 'aspect-ratio' working correctly, it throws up this error in the console.

### Example code
`<progressive-img :src="result.img" placeholder="http://via.placeholder.com/350x350" aspect-ratio="1" />`

### Environment
vue-progressive-image@2.3.1

![image](https://user-images.githubusercontent.com/12260295/32102148-fc99803c-bb12-11e7-9dea-7f0d1f236c54.png)

**Comment by MatteoGabriele** [comment]
Hi @james-clare 
you need to add the colon to the attribute so it will parse it as a number

```js
<progressive-img :aspect-ratio="1" />
```
