### ISSUE TITLE
Editable CSS

### ISSUE THREAD

**Issue by Pinch1A** [MatteoGabriele/vue-progressive-image#29]
Would be really handy have total access to the image itself and control dims and positioning of the `<img>` elem.

**Comment by MatteoGabriele** [comment]
Well that's not really possible: all positioning are done via javascript/css calculations.
If you want to change some CSS properties you need to target the component and do it the old school way: overriding CSS.
If you have some special use cases please drop a more specific issue, but this request at this moment can't be done.

thanks for your feedback :)
