### ISSUE TITLE
Not compatible with runtime-only build of vue

### ISSUE THREAD

**Issue by Julien76** [MatteoGabriele/vue-progressive-image#3]
Hi,

I'm trying to use your library in my project, however it fails for not being compatible with the runtime-only Vue:

    [Vue warn]: You are using the runtime-only build of Vue where the template option is not   available. Either pre-compile the templates into render functions, or use the compiler-included build. 
    (found in component <progressive-img>)

As the runtime-only output a smaller size bundle, that would be great if you could provide a compiled version of vue-progressive-image.

Also as a side note, are you considering an option to define srcset  for multiple image resolutions?

Thanks :)

**Comment by MatteoGabriele** [comment]
hi @Julien76 
I recently switch to runtime-only and i saw this error as well. I will definitely make a refactor 

thanks :)

**Comment by Julien76** [comment]
Great, thanks for the very fast asnwer :) Looking forward to use it 👍

**Comment by MatteoGabriele** [comment]
@Julien76 apparently the runtime-only is not compatible with the other way of build Vue. 
I thought that this setup was compatible for both.

I'll probably need to bump up a major version to maintain compatibility.

**Comment by MatteoGabriele** [comment]
Never mind I've found the problem! now it works 🎉 

I'll publish a new patch as soon as possible!

**Comment by MatteoGabriele** [comment]
@Julien76 published new v1.4.0

**Comment by MatteoGabriele** [comment]
@Julien76 For the `srcset` see #4 
I'm going to implement that as soon as I can :)

**Comment by Julien76** [comment]
Great stuff. Thanks a lot and sorry for late reply :)

**Comment by visualcookie** [comment]
Still not working for me.

` Unknown custom element: <progressive-img> - did you register the component correctly? For recursive components, make sure to provide the "name" option. `

**Comment by MatteoGabriele** [comment]
hi @visualcookie I can't really reproduce it, do you have a repo where i can check this issue you have? thanks a lot!

**Comment by visualcookie** [comment]
Now it works for me. Had some issues inside my `Vue.use()` usage.

**Comment by ruchikarnawan** [comment]
hello @visualcookie can you tell me how to fix `Unknown custom element: <progressive-img> - did you register the component correctly? For recursive components, make sure to provide the "name" option.` Thanks

**Comment by visualcookie** [comment]
@ruchikarnawan You have to define vue-progressive-image where you have your Vue instance starting, like so:

``` javascript
import vue from 'vue'
import VueProgressiveImage from 'vue-progessive-image'

Vue.use(VueProgesseiveImage)

/* ---- REST OF YOUR CODE ---- */
```

**Comment by ruchikarnawan** [comment]
So it turns out this define method
`var vueProgressiveImage = require('vue-progressive-image');`
is different with this
`import VueProgressiveImage from 'vue-progessive-image'`

I'm new with vue, so I thought it was the same way, 🤣 
Thanks @visualcookie and thanks @MatteoGabriele for the awesome plugin  🥂 🎉

**Comment by MikeChongCan** [comment]
@ruchikarnawan 

Just encountered this issue, I am using TypeScript at present time, in which `import` statement is restricted to cases for libraries with type definition. Consequently, I have to use `require()`.

This should work in my case:

```js
var vueProgressiveImage = require('vue-progressive-image').default;
```
