### ISSUE TITLE
canvas is undefined if progressive-background is not mounted

### ISSUE THREAD

**Issue by marklundin** [MatteoGabriele/vue-progressive-image#30]
### Description

When a `progressive-background` image is declared in JSX but is not displayed/mounted because of a `v-if` flag, it will throw an `TypeError: Cannot read property 'getContext' of undefined`

### Expected behavior

The lib should either only load the image when mounted, or pre load but not draw to the canvas

### Actual behavior

[getContext](https://github.com/MatteoGabriele/vue-progressive-image/blob/477d6c6b9a4adb9e54934afda0ed62985aba6055/src/mixin/image.js#L153) is called but the canvas object does not exist yet

**Comment by MatteoGabriele** [comment]
Hi @marklundin 
I can't reproduce this error, to be honest: also because I can't not even use v-if in jsx and vue
could you provide a reproduction of your issue in a public repo?

Thanks a lot for your feedback

**Comment by marklundin** [comment]
Hi @MatteoGabriele, I've put together [a reproduction](http://requirebin.com/?gist=5df501ca218095d63c6a2e15989118c1), although it's slightly different to what I originally thought.

In this instance I'm creating a `progressive-img` and the immediately unmounting it. Internally this causes the img.load to kick off, but by the time the load finishes the component has been unmounted. Should just be a matter of removing event listeners if the component is unmounted

**Comment by MatteoGabriele** [comment]
@marklundin I got the point now. 
thanks for your time!

**Comment by marklundin** [comment]
🤘

**Comment by MatteoGabriele** [comment]
:ok_hand:
