### ISSUE TITLE
Why "width: 100%; height: auto" doesn't work ?

### ISSUE THREAD

**Issue by luiztsmelo** [MatteoGabriele/vue-progressive-image#31]
I'm trying to make the img responsive with these css attributes, but it doesn't work. Why? What can I do to make it responsive?

**Comment by MatteoGabriele** [comment]
The image is already responsive: what's the issue?
could you make an example and explain better what's happening?

thanks :)

**Comment by luiztsmelo** [comment]
Well, I forgot what was happening here, but it's all working now. Sorry for inconvenience

**Comment by MatteoGabriele** [comment]
no problems! 
If you remember what's happening or it happens again, feel free to open it again

thanks
