### ISSUE TITLE
Scroll stutter

### ISSUE THREAD

**Issue by maxim25** [MatteoGabriele/vue-progressive-image#33]
Hi,

I've noticed that when using this library with multiple images (not many, maybe 8), the scroll becomes jagged. And when replacing the progressive-background component with simple images the lag seems to be gone.

Has anyone else experienced issues like this? Any idea on how to remedy this?

note:

In chrome dev tools rendering, when turning on "Paint Flashing" and "Scrolling Performance issues" nothing comes up. Also Chrome seems to be the most affected.

**Comment by maxim25** [comment]
Edit: 

By the looks of it, if I remove the placeholder after the images are loaded the scroll is smooth again.
Also, it only seems to affect progressive-background, progressive-img works fine.

**Comment by MatteoGabriele** [comment]
hi @maxim25 
unfortunately I can't reproduce it! could you be so kind to make a small reproduction in a public repository?

thanks a lot

cheers

**Comment by maxim25** [comment]
Thanks, I'll try to get a simple reproduction up sometime today.
Otherwise this repo is working great!

In the meantime, this is my code:

`<no-ssr>
        <progressive-background
          class="listing__image"
          :src="mainImage"
          :placeholder="placeholderImage"
          no-ratio>
        </progressive-background>
   </no-ssr>`

mainImage is a simple 512X512 jpg
placeholderImage is a simple 27X27 jpg

As I said, when I exclude the placeholder it doesn't lag at all.

**Comment by maxim25** [comment]
# @MatteoGabriele 

I've created a simple reproduction of the issue:
[https://github.com/maxim25/prog-image-bug](https://github.com/maxim25/prog-image-bug)

**Comment by MatteoGabriele** [comment]
@maxim25 thanks for your help!
I see the scroll behavior that you said, but I don't know why it works fine with the image and it doesn't with background.
The only think I can come up with is that, the background handling is more on the CSS that in the DOM, so it kinda less performant but... I'm just guessing, to be honest.

I will have a look, but feel free to share a possible solution if you have one in mind

thanks a lot!

**Comment by maxim25** [comment]
When you delete the placeholder the issue disappears. What do you think about deleting the placeholder node after the main image is loaded?

**Comment by maxim25** [comment]
@MatteoGabriele the following sorta seems to work, however the stutter persists until all images are loaded.

mixin/image.js
```javascript
// next tick to know when the image is rendered
this.$nextTick(() => {
  // timeout for a custom delay
  setTimeout(() => {
    this.isRendered = true
    // Remove placeholder image
    this.placeholderImage = null
  }, delay)
})
```

Edit:

I think I have found the main culprit: translateZ

I know the hack is supposed to yield a performance gain, but by the looks of it it is doing the exact opposite in this case. I propose to remove it, as well as set placeholderImage to null. I get a steady 60fps when I do so.

**Comment by MatteoGabriele** [comment]
@maxim25 Cool man, thanks!
I'm gonna try it right away!

**Comment by MatteoGabriele** [comment]
@maxim25 the update is available with the 2.4.2

thanks a lot for your feedback!

**Comment by maxim25** [comment]
@MatteoGabriele Awesome, thanks!

**Comment by maxim25** [comment]
@MatteoGabriele 

Looks like the following now causes a flicker during image load:

https://github.com/MatteoGabriele/vue-progressive-image/blob/141c2d3886a1cd0aec7bd2a0d37f7acccc4c076f/src/mixin/image.js#L171

Might as well remove that line, the translateZ fixes the scroll lag regardless.

**Comment by maxim25** [comment]
Hi @MatteoGabriele, did you see my message above by any chance?

**Comment by MatteoGabriele** [comment]
Hey @maxim25 yes I saw it :)
unfortunately I'm a bit busy this period. I will have a look as soon as possible.

Thanks a lot

**Comment by MatteoGabriele** [comment]
hi @maxim25 
I really can't see any problems. if you can create a reproduction of this issue would be great, otherwise I can't help you.

thanks again!

**Comment by MatteoGabriele** [comment]
I close this issue for inactivity. Feel free to re-open it once you provide a reproduction

thanks

**Comment by maxim25** [comment]
@MatteoGabriele Hi, sorry just been super busy. I'll create a reproduction/pull request in the next couple days! Cheers
