### ISSUE TITLE
Is this module tested on Safari?

### ISSUE THREAD

**Issue by coolemur** [MatteoGabriele/vue-progressive-image#34]
### Description

A bug ?

### Expected behavior

Smooth image change from blured to normal image.

### Actual behavior

In Safari Version 11.0.1 (13604.3.5) when image is loaded it doesn't change smoothly. It flashes with white background and then slowly shows image.

(In Chrome it works flawless.)

### Environment

`npm ls vue-progressive-image`: 
└── vue-progressive-image@2.4.2 
Then, specify:

1. Operating system:
Mac OS High Sierra
Version 10.13.1 (17B1003)

2. Browser and version:
Safari Version 11.0.1 (13604.3.5)

### Reproducible Demo
// Just a background image in container:
...
```
    <div style="width: 100%; height: 300px;">
      <progressive-background
        :src="background"
        :placeholder="backgroundLow"
      />
    </div>
```
...

```
  computed: {
    background () {
      return require('../../assets/tech.jpg') // huge image
    },
    backgroundLow () {
      return require('../../assets/tech-low.jpg') // small image
    }
  },
```

**Comment by MatteoGabriele** [comment]
It actually was but I didn't check after latest updates to be honest.
I'll need to check again.
Thanks for the feedback

**Comment by MatteoGabriele** [comment]
I don't have any issues on safari and I have your same exact machine. 
If you could create a github repo with a reproduction of this error would be perfect, otherwise I really can't see anything wrong.

Thanks for your feedback
