### ISSUE TITLE
New Feature Request: Lazy Loading

### ISSUE THREAD

**Issue by kingofwhales** [MatteoGabriele/vue-progressive-image#35]
Is lazy loading possible with this plugin?

It would be nice to have lazy loading on top of this blurry progressive loading. Thanks!!

**Comment by MatteoGabriele** [comment]
Yeah it's actually a feature that I would like to add.
Don't know if I will have time right now, but will probably be done.
If you want to you can obviously contribute to the plugin with a PR, would be really appreciated! :)

Cheers!

**Comment by bovas85** [comment]
I'm not sure how you'd be able to load the src image programmatically rather than asap.
Since you made the mixin, can you let me know how?

I'd use something like https://github.com/heavyy/vue-intersect/blob/master/README.md
vue-intersect to load the image when in the viewport. 
This uses intersection observer

**Comment by MatteoGabriele** [comment]
@bovas85  too be honest, lazy loading it's also not super user friendly if we talk about it in terms of _start loading only what you see when you see it_.
I think that images in the website should all slowly start loading so to have a smooth website with all in place without content staggering: that was my initial purpose for this plugin.

What do you want to know about the mixin?

**Comment by bovas85** [comment]
My idea is more to load images below the fold after dom load. This is mainly for grids of images, portfolios and blog articles where images might be below the fold.

An easy way is to set an intersect and switch on a data property when intersected, allowing the v-if to trigger and loading (lazily) these missing images.

**Comment by MatteoGabriele** [comment]
Yeah, that is something that I understand. Could be useful.
I'll have a look at the library you mentioned.

Thanks :)

**Comment by cloudbluedigital** [comment]
are there any plans for this feature? I have tons of images and google page speed is complaining about loading them when not visible

**Comment by MatteoGabriele** [comment]
@cloudbluedigital had a lot of work lately so, to be honest, still don't know. Maybe this weekend :)
if u have time and want to try, PRs are always open

thanks

**Comment by MaximStone** [comment]
> My idea is more to load images below the fold after dom load. This is mainly for grids of images, portfolios and blog articles where images might be below the fold.
> 
> An easy way is to set an intersect and switch on a data property when intersected, allowing the v-if to trigger and loading (lazily) these missing images.

Feature really useful. But for now i'm using https://www.npmjs.com/package/vue-intersect for add progressive-image in DOM when I want it to be loaded.
