### ISSUE TITLE
Option 'placeholder' isn't working when is used Vue.use(...)

### ISSUE THREAD

**Issue by hjJunior** [MatteoGabriele/vue-progressive-image#37]
### Description

Placeholder config in option doesn't work how I expected, just work if I setup in each component, I'm trying to define a default for all components the same placeholder.

### Expected behavior
I expect that setup made here changes all components in JSX mode
```
Vue.use(VueProgressiveImage, {
  placeholder: 'https://unsplash.it/1920/1080?image=20'
})
```
Using now just this
```
  h('progressive-img', {
    attrs: {
      src: 'someurl.here'
    },
    style: {
      width: '170px',
      height: 'auto',
      mixBlendMode: 'multiply',
      backgroundBlendMode: 'darken',
      marginBottom: '5px'
    }
  })
```
### Actual behavior

When I'm using this, just works if I setup for each component like this:

    h('progressive-img', {
      attrs: {
        src: params.row.miniatura,
        placeholder: 'https://media.giphy.com/media/cZDRRGVuNMLOo/giphy.gif'
      },
      style: {
        width: '170px',
        height: 'auto',
        mixBlendMode: 'multiply',
        backgroundBlendMode: 'darken',
        marginBottom: '5px'
      }
    })

### Environment

`npm ls vue-progressive-image`:  `-- vue-progressive-image@2.4.2`

Then, specify:

1. Operating system: Windows 10
2. Browser and version: Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)

### Reproducible Demo

The code was informed before

**Comment by MatteoGabriele** [comment]
@hjJunior thanks for your feedback 
Please, take your time to add a public repository that replicates this behavior.

thanks for your time
