### ISSUE TITLE
Pulling in from npm doesn't reflect latest features (e.g. alt prop)

### ISSUE THREAD

**Issue by admench** [MatteoGabriele/vue-progressive-image#39]
### Description

I pulled the package in from npm using `yarn add vue-progressive-image` getting version `2.4.2` (confusingly this repo's releases only goes up to `v.2.3.1` as of 22nd Jan 2018)

### Expected behavior
New alt tag feature implemented on 8db454ba272bf50d63ca7073a6e21eb5ec4a1eda should be available

### Actual behavior

Alt tag not available as a prop

### Environment

`npm ls vue-progressive-image`: vue-progressive-image@2.4.2

Presumably this is an issue with Npm not pulling in the latest github changes due to a release tag issue?
Many thanks for your great work :-)

**Comment by MatteoGabriele** [comment]
hi @admench 
I'm sorry for that, don't know why but it wasn't deployed correctly.

you can find the feature in the new vue-progressive-image@2.4.3

Thanks for your feedback :)

**Comment by admench** [comment]
Thank you, worked a treat!
