### ISSUE TITLE
FEATURE - Using srcset and different image breakpoints

### ISSUE THREAD

**Issue by bovas85** [MatteoGabriele/vue-progressive-image#40]
Can we add support (if not already present) for srcset and different breakpoints?

**Comment by MatteoGabriele** [comment]
I already tried that road here https://github.com/MatteoGabriele/vue-progressive-image/issues/4
but it's very complicated and I don't know how to handle that.

feel free to make a PR if you have any ideas, otherwise I will close it, since the other one was open for a while but nobody had the chance to code on it.

Thanks

**Comment by bovas85** [comment]
I've wrapper this component into my component and load a different size depending on window innerWidth. 

This works for me but a more generic code might be needed. I'll see if I can send a pr to the actual component itself

**Comment by MatteoGabriele** [comment]
@bovas85 thanks a lot for your time, if you could also just share the example you are talking about would be nice, so that I can have a bigger picture.

feel free to go with a PR, some help is more then welcome :)

**Comment by bovas85** [comment]
Yep will do tomorrow if I get the chance

**Comment by isuke01** [comment]
Actually it can be done by using https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Testing_media_queries
Here come also  smal pack https://www.npmjs.com/package/matchmedia-polyfill if you need.

**Comment by bovas85** [comment]
@isuke01 browser support seems a bit lacky and requires a polyfill, which increases bundle size I guess.
I'll PR my option although it's not super pretty but definitely lighter.

**Comment by bovas85** [comment]
Actually I can't as the logic is very different, the easiest option for me seems to be to wrap into another component passing my props to it, then v-if else load the component depending on the window size, passing a different image size to it.
Image below shows the usage:
![code](https://user-images.githubusercontent.com/16958684/36602320-a2f1ba90-18af-11e8-9843-7e17e2e96340.png)

You can see $root.isMobile $root.isTablet are checked on window resize and on mounted, to determine innerWidth of the viewport, this is reactive.

**Comment by MatteoGabriele** [comment]
@bovas85 could be possible to create a container component for this feature maybe

**Comment by bovas85** [comment]
It's a container component indeed. I called it LazyImage

I wouldn't know how to include it on your repo though

**Comment by MatteoGabriele** [comment]
well if already exists then doesn't make sense to add it to this one.

**Comment by bovas85** [comment]
No what I meant is to add it as a functionality built in into it. That's ok I'll use it this way. Thanks anyway

**Comment by MatteoGabriele** [comment]
I thought was already a package, we can still add it, you just create a new component and then you call it when you need to do lazy loading stuff

**Comment by bovas85** [comment]
@MatteoGabriele what you can see in the screenshot is my component that wraps around your plugin. The issue with me helping is that I wouldn't know how to replicate that in your package.

**Comment by MatteoGabriele** [comment]
No idea, let me know if u can wrap it in a small repository with an example and I'll see if it works.

Thanks again

**Comment by mortennh** [comment]
Why not try to orientate on the `<picture>` element itself? I could imagine something like this would be easy to maintain:

#### Picture Markup
```
<picture>
  <source media="(min-width: 56.25em)" srcset="large.jpg">
  <source media="(min-width: 37.5em)" srcset="medium.jpg">
  <source srcset="small.jpg">
  <img src="fallback.jpg" alt="">
</picture>
```
#### Progressive-img 

```
<progressive-img src="https://unsplash.it/1920/1080?image=10" placeholder="https://unsplash.it/1920/1080?image=10" :blur="30">
    <progressive-src  :srcset="srcSet(img.medium.src)" :sizes="sizes(img.medium.sizes)" :type="type(img.medium.type)" />
    <img src="fallback.jpg" alt=""> <--! Maybe unecessary  -->
</progressive-img>
```

**Comment by 3erikpotter** [comment]
> Actually I can't as the logic is very different, the easiest option for me seems to be to wrap into another component passing my props to it, then v-if else load the component depending on the window size, passing a different image size to it. Image below shows the usage: ![code](https://user-images.githubusercontent.com/16958684/36602320-a2f1ba90-18af-11e8-9843-7e17e2e96340.png)

Thank you for this example. I wound up doing similarly. For one-time use, it's just a matter of using v-if and a function that determines the screen size. It's pretty clean already but ofc could be further extracted into a component. It's a matter of taste and needs how many different screen types do we recognize. I opted for 3.

<img width="856" alt="Screenshot 2023-09-30 at 11 00 33" src="https://github.com/MatteoGabriele/vue-progressive-image/assets/8831134/6e9ff8d8-3c28-431e-91d9-0ab65c0bdeb6">
I think this could be a relatively easy addition to this library.
