### ISSUE TITLE
Problem using webpack (laravel 5.3 elixir) build

### ISSUE THREAD

**Issue by ejlocop** [MatteoGabriele/vue-progressive-image#42]
Hi, i can't show you a reproduction link right now but i will as soon as i can. i just really need to fix or find another solution to fix this issue.

so, the problem is with the webpack. when i'm using just the `gulp watch`, it runs ok.. 
but when i tried to run `gulp --production`. i got this error. 
can you tell me why? thank you.
```
app.js:39 Uncaught TypeError: Cannot read property 'image' of undefined
    at Image.e.onload (app.js:39)
e.onload @ app.js:39
```

**Comment by MatteoGabriele** [comment]
Hi @ejlocop 
Sorry but I can't help you like this. 
Besides that you didn't fill in the template for the issue, I have no idea about what is your project, what is your build process and what are you doing in your application.

I will wait few days for a reproduction done with `vue-cli` in a small application

**Comment by MatteoGabriele** [comment]
closed for inactivity
