### ISSUE TITLE
image stretches

### ISSUE THREAD

**Issue by MatteoGabriele** [MatteoGabriele/vue-progressive-image#43]
The image width should always be max the width of the image, not of the window

**Comment by 8bu** [comment]
nvm I fixed this bug with some global css. The no-ratio worked well. But I have to modify the css to make the image show up

**Comment by MatteoGabriele** [comment]
Can you paste the css you used? I didn't have time to work on it but I will :)

Thanks

**Comment by 8bu** [comment]
Sorry for not replying immediately, I didn't check the git notification last month.
I will review your source code and submit a pull request to fix this issue. Maybe next week

**Comment by MatteoGabriele** [comment]
@8bu any luck with this one? thanks again for your support
