### ISSUE TITLE
relative image path

### ISSUE THREAD

**Issue by MatteoGabriele** [MatteoGabriele/vue-progressive-image#44]
is it possible to just add the relative image path or it is mandatory to require the image and then serve it as a computed value?

**Comment by vincebanzon** [comment]
I can't load the image base from my relative path also. How do we get it to load?

**Comment by MatteoGabriele** [comment]
yeah I need to look at it, it's mostly a webpack problem because the plugin and your application don't share the same webpack instance but for now you can just create a computed value and do like 

```js
export default {
  name: 'MyComponent',

  computed: {
    image () {
      return require('assets/my-image.jpg')
    }
  }
}
```
and then pass it to the component

**Comment by MatteoGabriele** [comment]
is not possible to use relative paths because webpack of plugin and the application are different.

the only way of using the `src` or `placeholder` attributes is with a normal URL like the examples in the documentation

or using `require` to return the full path of the picture from webpack

```js
export default {
  computed: {
    image: () => require('@/assets/logo.png')
  }
}
```

or importing the image directly as a file and then add it to the component

```js
import image from '@/assets/logo.png'

export default {
  data () {
    return {
      image
    }
  }
}
```
