### ISSUE TITLE
New Feature Request: Config to remove console logs

### ISSUE THREAD

**Issue by cvince** [MatteoGabriele/vue-progressive-image#45]
I'd prefer that this library doesn't contribute console.logs in a production app. 
Would be nice if we could make this configurable.

I'd be happy to contribute with a PR if you don't have time to get to it.

**Comment by MatteoGabriele** [comment]
hi @cvince what do you mean with that?

**Comment by cvince** [comment]
wrong library.. sorry! 
Meant to comment on this one https://github.com/ccforward/progressive-image

**Comment by MatteoGabriele** [comment]
no problems! 😄
