### ISSUE TITLE
Adding 'alt' text to the image

### ISSUE THREAD

**Issue by AleksueiR** [MatteoGabriele/vue-progressive-image#47]
Is it possible to add the `alt` attribute to the generated image? It seems not possible right now.

**Comment by MatteoGabriele** [comment]
Hi @AleksueiR 
it is already possible 

```html
<progressive-img alt="test" src="https://unsplash.it/1920/1080?image=10" />
```

if you still have the problem, re-open the issue with a small application done with vue-cli so that I can have a look

thanks
