### ISSUE TITLE
Suggestion: Read image from File object

### ISSUE THREAD

**Issue by mikerockett** [MatteoGabriele/vue-progressive-image#49]
I'm using this component as part of an editing page where a feature image may be updated. The `src` is bound to `feature_image` in state, and when the user selects a new image, this piece of state changes from a string containing the URL of the image, to the `File` object that will uploaded on save.

My suggestion is to have the component detect if the `src` is an instance of a file and, if so, read its contents and display the image.

Would this be possible?

Thanks for the great component, works well in my project. 👍

**Comment by MatteoGabriele** [comment]
Hi @mikerockett 
I'm sorry but I don't think that this will be a feature that I will implement: it's a very edge-case use, very specific to your needs.
I will stick to support just plain images as the normal `img` tag does, with few extras

thanks for your suggestion tho

**Comment by mikerockett** [comment]
No problem at all, I have it working now. :)
