### ISSUE TITLE
Feature request: setting class names for <img> element

### ISSUE THREAD

**Issue by awmottaz** [MatteoGabriele/vue-progressive-image#50]
I would like an option to add class names to the `<img>` element within this component. For example,

```
<progressive-img src="/my-image.png" img-class="foo"/>
```

will render the component markup with the `<img>` element having the usual `progressive-image-main` class as well as the `foo` class.

**Comment by MatteoGabriele** [comment]
Thanks for the suggestion

I'll add this in the next release
