### ISSUE TITLE
dynamic background image not changed

### ISSUE THREAD

**Issue by volkanciloglu** [MatteoGabriele/vue-progressive-image#51]
When I change the page number, the old background image appears. When I change each page number, the previous background is displayed.

**Comment by MatteoGabriele** [comment]
I'm sorry but this comment doesn't make any sense to me: always remember that I don't have any context of the way you're using this plugin or where.

Please make a repository with vue CLI, very basic, and create there the example so I can see it

Thanks

**Comment by MatteoGabriele** [comment]
closed due to inactivity
