### ISSUE TITLE
Feature request: convert no-more and no-results texts to configurable variables

### ISSUE THREAD

**Issue by helariL** [MatteoGabriele/vue-progressive-image#52]
It would be awesome to make these texts configurable by the user 

`No results :(`

`No more data :)`

BR's

**Comment by MatteoGabriele** [comment]
Sorry @helariL, but which text are you talking about?
I don't fully get it.

thanks

**Comment by helariL** [comment]
I'm so sorry. Created the issue under wrong project.... 

I combined vue-progressive-image with vue-infinite-loading and this is how the mixup happened.

Once again, sorry.

**Comment by MatteoGabriele** [comment]
@helariL no worries! happens :)
