### ISSUE TITLE
disable margin-bottom

### ISSUE THREAD

**Issue by ondrejlohnisky** [MatteoGabriele/vue-progressive-image#53]
Is possible to disable the padding?

**Comment by MatteoGabriele** [comment]
Yes, you can use the no-ratio attribute
https://github.com/MatteoGabriele/vue-progressive-image/blob/master/README.md#ratio

**Comment by ondrejlohnisky** [comment]
I know. But when i add no-ratio attribute to the element and save the problem doesn’t get solved.
I have margin-bottom about 5 px.
Is there other way to change the margin-bottom? Or try to fix that.
