### ISSUE TITLE
no-ratio issue

### ISSUE THREAD

**Issue by ondrejlohnisky** [MatteoGabriele/vue-progressive-image#54]
When i add no-ratio the image is not visible.
My problem is that my images got margin-bottom and if i add no-ratio attribute to image it become invisible.

**Comment by MatteoGabriele** [comment]
hey @ondrejlohnisky sorry for the delay I text you back.
Could you create a repo with this behavior and link it here.

Thanks a lot

**Comment by ondrejlohnisky** [comment]
its okay now :) 
I don't even know what is this about :D
