### ISSUE TITLE
Feature request: class props

### ISSUE THREAD

**Issue by natemate90** [MatteoGabriele/vue-progressive-image#56]
I would like to add some classes to the nested `<progressive-background>` component, in order to style the background better (background-position, etc.). This would work great together with Tailwind CSS. Right now, the class names seem to be given random names (i.e. _30VsZs3N14iSeemk3xHHZL_0).

**Comment by MatteoGabriele** [comment]
hi @natemate90 
yes I use css modules to avoid class names collisions and so class names are generated on build time and they are not human readable.

I need to find a way to make this possible, not sure yet :)
Unfortunately is not on my list of top priorities right now, I have other packages to take care of, so if you want to take a look at the code and propose a PR, that would be awesome!

thanks for the suggestion.

**Comment by natemate90** [comment]
I understand. Thanks for your quick response! Maybe I might be able to work on this in a while, when I have more time as well :)

**Comment by MatteoGabriele** [comment]
I've added the possibility to use the `custom-class` property that will add a class or classes to the root element and in addition I've removed CSS-Modules and moved to normal CSS for both progressive-image and progressive-background so should also be easier to select the elements.

**Comment by natemate90** [comment]
Thanks a lot!
