### ISSUE TITLE
Can this plugin be used in a VuePress@next site?

### ISSUE THREAD

**Issue by rchrdnsh** [MatteoGabriele/vue-progressive-image#57]
Not a bug but a question:

Is it possible for this plugin to be used in a VuePress@next web app? They are instituting plugins for VuePress 1.0 and I was wondering if anything different would need to be done to be able to use this in a vuepress 1.0 app.

That's all :-)

**Comment by MatteoGabriele** [comment]
Well, technically should work but I have never tried. Works with SSR applications so I don't see problems. Try it and let me know :)

**Comment by MatteoGabriele** [comment]
I'm going to close this one for inactivity but please come back with some news if you have them

thanks

**Comment by rchrdnsh** [comment]
oh yeah, no worries, VuePress is working out a few bugs in alpha...I'll come back around with this when it's stable enough to work consistently :-)
