### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by Cobrand** [MatteoGabriele/vue-progressive-image#58]
This is not really a bug so I'll take the liberty to not use the template.

Basically 

```
git clone https://github.com/MatteoGabriele/vue-progressive-image
pushd vue-progressive-image/examples
npm install
npm run build
```

returns 

```
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module not found: Error: Can't resolve '@/components/thumbnailsWithFallback' in '/home/cobrand/Code/vue-progressive-image/examples/src'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 14:0-73
 @ ./src/App.vue
 @ ./src/main.js
```

(this also happens with `npm run dev`). I've followed the README inside examples/. Is a step missing by any chance?

**Comment by MatteoGabriele** [comment]
hi @Cobrand I'm gonna have a look asap

thanks for your feedback

**Comment by MatteoGabriele** [comment]
I think you didn't run the dev server in the proper folder: you need to go inside the /example folder, install dependencies and run dev inside there.
