### ISSUE TITLE
I do u get/generate the low resolution image of original image file

### ISSUE THREAD

**Issue by kamit-transient** [MatteoGabriele/vue-progressive-image#62]
Hey Guys,

I need a quick help to understand, how do you guys are generating low resolution image for your original image.

are you putting both version on your server or how does this works. I tried to google it but looks like I am missing something.

**Comment by MatteoGabriele** [comment]
I personally use Photoshop to downscale my image down till 3kb and then use the full resolution as the main image. I store it in the domain but I know there's also an Amazon service that does this on the fly for you. You should check, hope I'm not wrong and should be Amazon

Cheers
