### ISSUE TITLE
Position:absolute breaks z-indexing in the rest of the document

### ISSUE THREAD

**Issue by j6k4m8** [MatteoGabriele/vue-progressive-image#63]
### Description

`.progressive-background-image`'s `position: absolute;` breaks z-indexing with the rest of the document.

### Expected behavior

Component should act 1-to-1 with <img> tag and sit "under" another element if given a lower z-index

### Actual behavior

These components render "on top of" all other components.

Perhaps this is by design? If so, might be worth documenting! Was tricky to track down!

**Comment by MatteoGabriele** [comment]
Yeah indexing is a pretty tricky bastard. The thing is that there are a lot of things inside this element taking care of positions, sizes, effects etc..
Did u fix it adding a lower index to the wrapper?

**Comment by j6k4m8** [comment]
Right — was able to get around this by redoing the rest of the surrounding DOM indexing "on top of" the progressive images.

**Comment by kgnfth** [comment]
i added this to my css and now everything looks normal as it was and progressive image still works

```css
.progressive-image {
  position: unset !important;
}
```
