### ISSUE TITLE
Add fallback threshold time

### ISSUE THREAD

**Issue by bsommardahl** [MatteoGabriele/vue-progressive-image#72]
I am having network issues today with unsplash. When this happens, my fallback will eventually be displayed. But that might be 10 seconds of waiting. I would prefer being able to set a 2 second threshold so that, if networking issues are happening, my fallback will be displayed faster.

**Comment by MatteoGabriele** [comment]
I am sorry for the delay 🤣  as you can see, I haven't been super responsive in this repo.
I will close the issue. Please feel free to re-open it if you have something to add about this issue because I didn't quite get the problem.
