### ISSUE TITLE
Not working properly in safari 

### ISSUE THREAD

**Issue by famedevelopment** [MatteoGabriele/vue-progressive-image#77]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

When I run this plugin in safari browser, there is no fade effect on image when it load.

### Expected behavior

Fade effect should work properly, when image is load, then image should smoothly show up to user

### Actual behavior

fade effect not work

### Environment

`npm ls vue-progressive-image`: 
impactcapital@1.0.0 /Users/ananas/Documents/IMPACT CAPITAL/app
└── UNMET DEPENDENCY vue-progressive-image@^3.2.0
npm ERR! missing: vue-progressive-image@^3.2.0, required by impactcapital@1.0.0

Ohh, It says that plugin is missing, but I actually have it in my project node_modules folder for sure

Then, specify:

1. Operating system: Ubuntu 18, MacOS 
2. Browser and version: Safari 13.1.2 (15609.3.5.1.3)

**Comment by MatteoGabriele** [comment]
sorry for the delay 🙏 
Works on safari for me. Please re open in case you need help
