### ISSUE TITLE
How to load on scroll?

### ISSUE THREAD

**Issue by kodekrendel** [MatteoGabriele/vue-progressive-image#8]
Hi.

Is there an option to load images as I scroll down? They all appears at one moment. I have at test page 5 images. I want them lazyload as I scroll down.

**Comment by MatteoGabriele** [comment]
hi @kodekrendel

no, there's option for that right now. every instance of the progressive image is standalone. locally they might load simultaneously but usually they don't ( depending on the quality ) 

if you want to do it yourself, you could just make a loop of the component and push images as you scroll down. the rest would be handled by the component's logic. 

i might gonna work on a feature like that :)

**Comment by kodekrendel** [comment]
> loop of the component

Hmm, how to do that? Not sure I understand. I'll be happy to try, if you elaborate. 

And I am surely will appreciate this feature out-of-the-box. I tried progressive-image package, but they have issue with my server-rendered Nuxt app. Your package seems like work fine with SSR which is nice already (got "client-side rendered virtual DOM tree is not matching server-rendered content" error in console, but all seems to be working fine tho), but doesn't have this feature (Medium-like loading, they also doesn't load images at once, even if they already downloaded).

**Comment by MatteoGabriele** [comment]
you need to calculate when the scroll reaches the bottom and push other images. Just made a quick example with a `setInterval` just to show you the _pushing_ part I was talking about :)

this is my component 

```js
export default {
  name: 'home',

  data () {
    return {
      images: [
        'https://unsplash.it/1920/1080?image=10',
        'https://unsplash.it/1920/1080?image=11',
        'https://unsplash.it/1920/1080?image=12',
        'https://unsplash.it/1920/1080?image=13',
        'https://unsplash.it/1920/1080?image=14',
        'https://unsplash.it/1920/1080?image=15',
        'https://unsplash.it/1920/1080?image=16'
      ],
      imagesToDisplay: []
    }
  },

  mounted () {
    let i = 0
    let max = this.images.length

    const imagePoll = setInterval(() => {
      if (i === max) {
        clearInterval(imagePoll)
        return
      }

      this.imagesToDisplay.push(this.images[i])

      i = i + 1
    }, 1000)
  }
}
```

and this is the view

```html
<script src="./my-component.js"></script>

<template>
  <div>
    <div>
      <div :key="index" v-for="(image, index) in imagesToDisplay">
        <progressive-img :class="$style.image" :src="image" :placeholder="image" />
      </div>
    </div>
  </div>
</template>
```

It's a super basic one, but if you change the interval with a scroll event that calculates when you reach the bottom of the page, you need to push images as it goes.

**Comment by kodekrendel** [comment]
Hm, I'm pretty sure that this *pushing* part is not what needed since it not very user friendly. By lazyloading I mean blur-opacity effect, not pushing. The place of image must be reserved for sure, imho.

**Comment by MatteoGabriele** [comment]
The images start lazyloading as soon as they are added to the DOM, that's why I said to push images into an array. 

Mine was only an example/workaround

**Comment by MatteoGabriele** [comment]
If you want the blur-effect you only need to add a placeholder, that's it and the amount is also configurable

**Comment by kodekrendel** [comment]
Agree, in that example hardcoded interval, may be in native implementation it will be more smooth, as far as I can imagine.

**Comment by kodekrendel** [comment]
There's a placeholder in your example: `:placeholder="image"`, or you mean tiny images? Then this will work other way?

**Comment by MatteoGabriele** [comment]
if you want a real progressive image you only need a compression tool like [ImageminPlugin](https://github.com/Klathmon/imagemin-webpack-plugin)

my progressive loading it's fake :)

To create di effect you need to images with the same aspect ration, the placeholder tho is a very very low quality version of the main image.

It's all written in the documentation

**Comment by kodekrendel** [comment]
Your progresssibve loading is fine for me, but the fact, that it trigger ALL images on page at once (I have 3 image in article, and I want that load effect WHEN user scroll to that image, not if that image in the viewport).

**Comment by kodekrendel** [comment]
Placeholder is not working. Seemse like that pushing is broke it.

**Comment by MatteoGabriele** [comment]
Yeah I got the point. It's not possible :)
At least not now.

My example works, just made it, but i was using this to have the effect 

```js
Vue.use(VueProgressiveImage, {
  delay: 1000
})
```

Locally they will just load at the same time because it's the same image

I'll see what I can do

**Comment by kodekrendel** [comment]
No, it's still loading images one by one and glitch scrollbar. Placeholder doesn't do that trick.

**Comment by kodekrendel** [comment]
In docummentation unclear how to use it:

```
export default {
  methods: {
    onLoadImage () {
      // main image is loaded
    },
    onLoadPlaceholderImage () {
      // placeholder image is loaded
    }
  }
}
```
What whould I leave it empty?

**Comment by kodekrendel** [comment]
I don't understand but placeholders doesn't work at all :smile:

**Comment by MatteoGabriele** [comment]
You should read also the text around the code: those are events triggered by the component, so you know when an image or its placeholder are loaded.

**Comment by MatteoGabriele** [comment]
This is the example i wrote you: and it works.
Every 2 seconds a new image is pushed and the blur kicks in and then the full hd image fades.

![screen recording 2017-04-27 at 10 34 pm](https://cloud.githubusercontent.com/assets/5337152/25503258/f90fb458-2b99-11e7-8905-22f9f5317925.gif)

**Comment by kodekrendel** [comment]
Strange. I have the opposite - http://five-burst.surge.sh/images2/

**Comment by MatteoGabriele** [comment]
The opposite?? Looks the same to me!

**Comment by kodekrendel** [comment]
How it the same - look at the scrollbar. It increase the page height! I want it PLACEHOLD)))

**Comment by kodekrendel** [comment]
There are NO space, untill image appears. I need it, to page not to give that pushing behaviour,

**Comment by MatteoGabriele** [comment]
if you want that you need to find a way to handle it yourself via CSS maybe or Javascript.
Right now the library only loads images independently: one by one.
If you put 20 images  they will start loading and add space almost immediately.

You want too much, this is not a website: it's a plugin :) 
You need to do the rest.

**Comment by kodekrendel** [comment]
@MatteoGabriele I don't want much, I want a placeholder :smile: 
On your screenshot it's clear that when you scroll down there's the space under Image. I don't know how you do that, but CSS has nothing to do with that for sure.

**Comment by kodekrendel** [comment]
> If you put 20 images they will start loading and add space almost immediately.

No they don't! That code will add space one by one image for 1 second. I don't know why your screenshot working other way.

**Comment by MatteoGabriele** [comment]
i just add 2000px height on the container. was only an example. the placeholder works, not for lazy loading on scroll.

**Comment by kodekrendel** [comment]
Ok, that explains. :smile: 

Anyway, thanks for your time. Well crafted plugin, and works out-of-box with SSR - and that's something I must say :+1:

**Comment by MatteoGabriele** [comment]
Thanks. 
The plugin was meant to be used for scenarios like thumbnails or images within content to avoid jumping of text or other divs, like in the gif in the documentation: not for lazy loading on scroll.

For that, you might need to wait until I find a way, if I find a way compatible with the nature of the component 

Thanks for your feedback :)

**Comment by MatteoGabriele** [comment]
so I'm going to close this one as a resolved question, make some tests and see if i can open a ticket for a sort of method to trigger the effect when images are in the viewport.

**Comment by kodekrendel** [comment]
Sure! And I after little research, still will stick with vue-progressive-image. Thanks!
