### ISSUE TITLE
Don't know how to get this to work in a vue-pwa, or a .vue single-file component...

### ISSUE THREAD

**Issue by rchrdnsh** [MatteoGabriele/vue-progressive-image#9]
Having trouble making this work in .vue single file component inside a vue-pwa template app...

first off... dunno where...

```javascript
Vue.use(VueProgressiveImage)
```

...is supposed to go or what it's purpose is. my 'main.js' file looks like this...

```javascript
// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.

import Vue from 'vue'
import App from './App'
import router from './router'
import VueProgressiveImage from 'vue-progressive-image'

Vue.use(VueProgressiveImage)

Vue.config.productionTip = false

/* eslint-disable no-new */

new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})
```

...dunno if that is how it's supposed to be set up in the main.js file.

So, the component .vue file I'm trying to add vue-progressive-images to looks like this inside the script tag:

```html
<script>
  import VueProgressiveImage from 'vue-progressive-image'

  export default {
    components: {
      'vue-progressive-image': VueProgressiveImage
    }
  }
</script>
```

...then I'm creating a slot in the template of the .vue file to use for the placeholder image tag, like so...

```html
<slot name="background-image"></slot>
```

...then I'm trying to add this progressive-image html tag to a slot in an instance of the component, like so...

```html
<progressive-img
        slot="background-image"
        src="../../assets/images/featured/venice-scene-1920x1200.jpg"
        placeholder="../../assets/images/featured/venice-scene-512x320-placeholder.jpg"
        alt="A sample google virtual tour."
      />
```

but I'm getting this error message for both the src and placeholder images:

<img width="513" alt="screen shot 2017-06-27 at 4 02 01 pm" src="https://user-images.githubusercontent.com/7884263/27613720-052fc682-5b52-11e7-9dea-eb1f795dcebe.png">

but that same file path worked just fine before I tried to add the progressive-img tag, so I'm confident that this is not the problem.

Anyway, don't know how to make this work or fix it, so anything you can suggest would be awesome!

Thank you :-)

R

**Comment by MatteoGabriele** [comment]
Hi rchrdnsh
Well basically when you use a plug-in you have to register it to the Vue instance calling the `use` method.

After that you don't have to import anything else, like in the examples, the components are available globally in your application.

Just use `<progressive-img src="image path here" />` and provide a placeholder image (possibly very small in size and with same aspect ratio of the original image) if have one, so you can have the nice blurry effect before the big image is loaded

If u can provide a simple repository, I could look into it.

Let me know

**Comment by rchrdnsh** [comment]
ok, let me set one up, then I'll share it with you :-)

**Comment by rchrdnsh** [comment]
I tried putting the images in the static folder, rather than the assets folder, and it works, so it seems to be an issue with how the plugin and Webpack work together maybe? I might be missing something that I need to add to make it work if I want to serve the images from the assets folder in the Webpack based template?

**Comment by rchrdnsh** [comment]
ok, got the plugin to work using images in the static folder, as I said before, but there are a few odd things going on that I don't know how to alter.

First off, I'm using the polymer technique of taking my original image and downsizing it to roughly 1 percent of it's original size. For example, I am downsizing 1920 by 1200 pixel images to 8 by 5 pixels, then compressing them and base64 encoding them. They end up being between 200 and 500 bytes.

This is one example of the resulting code:

```
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAFAAgDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAgEAABAwMFAQAAAAAAAAAAAAABAAIDBBESBQYTIVFx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAgT/xAAYEQADAQEAAAAAAAAAAAAAAAABAhEAcf/aAAwDAQACEQMRAD8An1Zqzpdk09VJECHnhEeZs1uRHy/XiIiLiSapmMHBv//Z

```
...which is around 400 bytes or so, and can be added inline in the html itself so no extra request needs to be made.

So...

The plugin itself is working, loading the placeholder, then the original image, except that the placeholder image is rendering at it's original 8x5px size, rather than being blown up to cover the same space as the full 1920x1200 image, which is my expected behavior. I don't know how to blow up the placeholder using CSS, as every technique I know did not work.

The second issue I noticed when I was using a placeholder the same size as the original image. When the placeholder loads there is a strange blurred white border around the placeholder image, which then goes away after the original image loads. It also felt as if the placeholder image zoomed in a little bit as well, although I couldn't really be sure. Both of these styling behaviors are not desired by me, but again, I'm sure how to alter them.

Anyway, still working on creating a repo, which I have never done before, so that might take me a sec, but let me know if you can assist in these other areas.

Thank you! 🤗

**Comment by MatteoGabriele** [comment]
well for the image size, my bad I said "size" but i was thinking about file size: the picture should be same width and height of the image you want to load. The trick is that if you reduce its quality you can have a super cheap image to use as a placeholder.

for the url, that's a webpack problem: when you pass something like `~assets/image/my-image.jpg` to a component webpack doesn't process it anymore, for it it's just a string that you are concatenating with the hostname i.e. `http://localhost:8080/~assets/image/my-image.jpg`

to be able to use a path with an alias you need to resolve it yourself and then pass it to the component or just use a static path.

if you setup this little reproduction of your issue I can have a look.

Let me know, hope i helped

**Comment by rchrdnsh** [comment]
hmmmm, I see. For me even a 0% quality image of the same size is still really big, so it does not really help me all that much. I suggest looking into the 200 byte pattern that many people are adopting and maybe try to support that option in the future :-)

Here is a video explaining the concept by Rob Dodson from Google Dev Rel:

https://www.youtube.com/watch?v=iAgSvlYavX0

and here is the web component of which Rob speaks of:

https://github.com/PolymerElements/iron-image

The magic is in the component, and after looking through some of the source code I have yet to figure out what makes it work. Perhaps you might better luck :-)

Anyway, thank you again for all your hard work in OSS Matteo. It is very much appreciated :-)

R

**Comment by MatteoGabriele** [comment]
Thanks a lot! Always nice to read that :)
I'll take a look at this documentation: it sounds interesting.

Besides this though, did u have time to make the example? Otherwise I can't help you that much. 

I might gonna make an example folder directly in the repo itself so that people can copy paste or at least understand how should work

**Comment by MatteoGabriele** [comment]
I close this issue for inactivity, open it in anytime if you provide more info.
ps: I'm working on an update that will provide the ability to add a very tiny image as a placeholder that will stretch as big as the main image.

**Comment by rchrdnsh** [comment]
awesome, keep me posted on your work on this, and thank you very much for your time and effort :-)

**Comment by MatteoGabriele** [comment]
@rchrdnsh it's already available with the latest version :)

**Comment by rchrdnsh** [comment]
sweet! will check it out then XD
